[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
warp = "0.3"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
local-ip-address = "0.6"
